### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by Roman19S** [rkoesters/xkcd-gtk#127]
**Is your feature request related to a problem? Please describe.**
Distros like Linux Mint and Elementary OS have started hiding or otherwise discouraging the use of unverified flatpaks. More will likely follow as verified apps approach 50% of Flathub

**Describe the solution you'd like**
Could you verify the flatpak on Flathub so people on these distros can find it?

**Describe alternatives you've considered**

**Additional context**
Here is a link to Flathub's verification documentation for app authors https://docs.flathub.org/docs/for-app-authors/verification/

**Comment by rkoesters** [comment]
Thanks for bringing this to my attention.

I've gone through the verification process on the Flathub developer dashboard. The Flathub listing still says "unverified", so perhaps there is some delay. I'll leave this issue open until the Flathub listing has refreshed.

I'm unable to locate documentation for verifying the app with elementaryOS's flatpak repository.

**Comment by rkoesters** [comment]
It now shows as verified on https://flathub.org/apps/com.github.rkoesters.xkcd-gtk
