### ISSUE TITLE
No valid categories in .desktop file

### ISSUE THREAD

**Issue by danrabbit** [rkoesters/xkcd-gtk#29]
Your .desktop file doesn't contain any valid categories for displaying it in AppCenter. You can review a list of valid categories and more information about writing .desktop files [here](https://elementary.io/docs/human-interface-guidelines#app-launchers)

I think for this app "Internet" would be the most appropriate primary category

**Comment by rkoesters** [comment]
Thanks for the heads up!

Fixed by 002506ef7ab0a967fbea4099c2ec0533ed9f0973
