### ISSUE TITLE
could you make a flatpak for xkcd-gtk?

### ISSUE THREAD

**Issue by chemel9** [rkoesters/xkcd-gtk#40]
Hi, I really appreciate your work , is a good application
but i don't use elementary OS
could you make a flatpak for xkcd-gtk?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by rkoesters** [comment]
I like the idea. I will try to get a flatpak in flathub by the 1.0.x release.

**Comment by rkoesters** [comment]
Now available on FlatHub: https://flathub.org/apps/details/com.github.rkoesters.xkcd-gtk

**Comment by chemel9** [comment]
Thanks (Y)
