### ISSUE TITLE
[Feature request] Night mode

### ISSUE THREAD

**Issue by pizzadude** [rkoesters/xkcd-gtk#47]
I think it would be cool to invert the colour of the comics with a button so it would be easier on the eyes to read at night.

**Comment by rkoesters** [comment]
Partially fixed by 32a6533b087a6ae339ae83d7f8e0684138ec9c02. It now supports dark gtk themes, but there isn't a toggle in the user interface for turning this mode on and off.

**Comment by rkoesters** [comment]
Fixed by b5406fb6429363abb14aa616f136818834412ab0. Release is blocked by https://github.com/elementary/stylesheet/pull/433.

**Comment by pizzadude** [comment]
Just to be clear, I mean the actual comics themselves, not just the gtk theme. Is that what you fixed?

**Comment by rkoesters** [comment]
Yes. It uses both the dark gtk AND it inverts the comic images.

**Comment by pizzadude** [comment]
Thank you!
