### ISSUE TITLE
[Feature Request] Favorites

### ISSUE THREAD

**Issue by ManIVIctorious** [rkoesters/xkcd-gtk#50]
Well first of all thank you for the effort you put into this application, especially the search works wonders.

I have one proposition:
Could you please implement some sort of favorite/staring mechanism, I often browse the comics in random order and every now and then you find this one you know you will need again.
It would be really nice if one could mark it as a favorite and browse the favorites afterwards

**Comment by rkoesters** [comment]
Bookmarks have been added as of ec38bddce1fb27aac06441857fd2fc6c44f3d521.
