### ISSUE TITLE
AppCenter: Question about 1.1.3 release

### ISSUE THREAD

**Issue by cassidyjames** [rkoesters/xkcd-gtk#51]
As far as I can see, the only thing from 1.1.2 to 1.1.3 is an AppData bump. Am I missing something? https://github.com/rkoesters/xkcd-gtk/compare/1.1.2...1.1.3

**Comment by rkoesters** [comment]
The xkcd package (https://github.com/rkoesters/xkcd) that communicates with the xkcd API was updated to account for changes in the text encoding delivered by the xkcd server.
