### ISSUE TITLE
Appdata translations not working

### ISSUE THREAD

**Issue by NathanBnm** [rkoesters/xkcd-gtk#56]
Hi, appdata translations are currently not working. You should take a look on it. I'm not experienced with Go so I don't know how to proceed.

**Comment by rkoesters** [comment]
They should be working, are you using the version in AppCenter/FlatHub or are you building from source?

If you are using the AppCenter/FlatHub version, then the reason that the translations aren't working is that I have not gotten around to publishing the next release, therefore the AppCenter/FlatHub version is an older version that doesn't have translations yet.

Hopefully, I will be able to find the time to publish the new version soon.

**Comment by NathanBnm** [comment]
I'm using the AppCenter version actually. Sure would be great to update :+1:

**Comment by rkoesters** [comment]
Comic Sticks 1.2.0 has been released with translations. However it may take some time to reach AppCenter.
