### ISSUE TITLE
Occasionally freezes when loading comic

### ISSUE THREAD

**Issue by Talinx** [rkoesters/xkcd-gtk#60]
When going to a previous or next comic (that is not cached) xkcd-gtk occasionally (about 1 in 30 times) freezes and with it the desktop environment.
The application manages to show "Loading comic..." and hangs up after that.

Version 1.3.2 on elementary OS.

**Comment by jamesMFelder** [comment]
I have the same problem.

Version 1.3.2 on Arch Linux.

**Comment by rkoesters** [comment]
I've experienced lag when the app does network operations with a slow or disconnected internet.

Is your machine connected to the Internet when the freezes occur?

**Comment by Talinx** [comment]
Yes, it is connected to the internet.

**Comment by rkoesters** [comment]
I've recently release version 1.4.0 on [flathub](https://flathub.org/apps/details/com.github.rkoesters.xkcd-gtk).

Please try that version out, and let me know if you still have issues.

**Comment by Talinx** [comment]
No more issues, thank you!

**Comment by rkoesters** [comment]
Awesome! Let me know if you experience these issues again.

While I'm not sure which change fixed your issue, I did make several improvements to the cache handling in these changes:

* d81a66b42bb9a40b81b3eef90e1775b9cc7b6965
* af3eca9cdf80efd4990a8124d2d87f3b0fe2b6ad
* dd0185123ae721b2e4490cf0eb05af2b979ca447
* d033b4f9717ee0d0dcf805ae5692af00e4ef3b80
* 9c005e18b9b4f2c15b6860a9006219a60e9a8dba
* 61fdb43d2a6bebedc5a6cd098741fe78081c9c79
